# Site settings
# Change these values to suit your site

# Basic info
name: My Personal Website
title: My Personal Website
email: your-email@example.com
description: >-
  Welcome to my personal website, blog, and portfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://yourusername.github.io" # your GitHub Pages URL

# Build settings
markdown: kramdown
theme: minima
permalink: /blog/:year/:month/:day/:title/
remote_theme: "mmistakes/minimal-mistakes"

# Collections
collections:
  portfolio:
    output: true
    permalink: /portfolio/:name/

# Navigation (optional)
nav:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Blog"
    url: "/blog/"
  - title: "Portfolio"
    url: "/portfolio/"
  - title: "Contact"
    url: "/contact/"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - README.md
  - .gitignore
  - .vscode

# Blog pagination
paginate: 5
paginate_path: "/blog/page:num/"

github:
  is_project_page: false
  # Set to true if deploying to a project page (https://username.github.io/repo)

# GitHub Pages build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
